{{- if .Values.ingress.enabled -}}
  {{- $fullName := include "node.fullname" . -}}
  {{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
  {{- else if semverCompare ">=1.14-0 <1.19.0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
  {{- else -}}
apiVersion: extensions/v1beta1
  {{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
  {{- include "node.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName | quote }}
  rules:
  {{- with .Values.ingress.rules }}
  {{- toYaml . | nindent 6 }}
  {{- end }}
  tls:
  {{- with .Values.ingress.tls }}
  {{- toYaml . | nindent 6 }}
  {{- end }}
{{- end }}