language: go
go_import_path: github.com/dapperlabs/flow-go

go:
  - 1.13

branches:
  only:
    - master

cache:
  bundler: true
  directories:
    - $HOME/.cache/go-build
    - $HOME/gopath/pkg/mod

before_install:
  - git config --global 'url.ssh://git@github.com/.insteadOf' https://github.com/

script:
  - make ci
