# See https://forum.bors.tech/t/bug-wildcard-status-ignores-1-match/438
# for why we need to explicitly list all statuses

status = [
  "Lint (./)",
  "Lint (./integration/)",
  "Lint (./crypto/)",
  "Unit Tests (access)",
  "Unit Tests (admin)",
  "Unit Tests (cmd)",
  "Unit Tests (consensus)",
  "Unit Tests (engine)",
  "Unit Tests (fvm)",
  "Unit Tests (ledger)",
  "Unit Tests (module)",
  "Unit Tests (network)",
  "Unit Tests (utils)",
  "Unit Tests (others)",
  "Integration Tests (make -C integration access-tests)",
  "Integration Tests (make -C integration bft-framework-tests)",
  "Integration Tests (make -C integration bft-gossipsub-tests)",
  "Integration Tests (make -C integration bft-protocol-tests)",
  "Integration Tests (make -C integration collection-tests)",
  "Integration Tests (make -C integration consensus-tests)",
  "Integration Tests (make -C integration epochs-cohort1-tests)",
  "Integration Tests (make -C integration epochs-cohort2-tests)",
  "Integration Tests (make -C integration execution-tests)",
  "Integration Tests (make -C integration ghost-tests)",
  "Integration Tests (make -C integration mvp-tests)",
  "Integration Tests (make -C integration network-tests)",
  "Integration Tests (make -C integration verification-tests)",

]

delete_merged_branches = true
required_approvals = 2
