apiVersion: v1
kind: Service

metadata:
  name: flow-collection-node-ingress-service
  namespace: flow

  labels:
    app: flow-test-net
    node: collection
    env: staging
    owner: Kan
    version: v1

spec:
  type: ClusterIP
  selector:
    app: flow-test-net
    node: collection
    env: staging
    version: v1
  ports:
    - name: ingress
      protocol: TCP
      port: 9000
      targetPort: ingress

---
# To pre-emptively prepare for the case where we'd want to connect to a specific collection cluster, we can have sub services per cluster

# Service for accessing the first collection cluster
apiVersion: v1
kind: Service

metadata:
  name: flow-collection-node-v1-0
  namespace: flow

  labels:
    app: flow-test-net
    node: collection
    env: staging
    owner: Kan
    version: v1

spec:
  type: ClusterIP
  selector:
    app: flow-test-net
    node: collection
    env: staging
    version: v1
    statefulset.kubernetes.io/pod-name: flow-collection-node-v1-0

  ports:
    - name: ingress
      protocol: TCP
      port: 9000
      targetPort: ingress
    - name: grpc
      protocol: TCP
      port: 3569
      targetPort: grpc

---

# Service for accessing the second collection cluster
apiVersion: v1
kind: Service

metadata:
  name: flow-collection-node-v1-1
  namespace: flow

  labels:
    app: flow-test-net
    node: collection
    env: staging
    owner: Kan
    version: v1

spec:
  type: ClusterIP
  selector:
    app: flow-test-net
    node: collection
    env: staging
    version: v1
    statefulset.kubernetes.io/pod-name: flow-collection-node-v1-1

  ports:
    - name: ingress
      protocol: TCP
      port: 9000
      targetPort: ingress
    - name: grpc
      protocol: TCP
      port: 3569
      targetPort: grpc

---

# Service for accessing the third collection cluster
apiVersion: v1
kind: Service

metadata:
  name: flow-collection-node-v1-2
  namespace: flow

  labels:
    app: flow-test-net
    node: collection
    env: staging
    owner: Kan
    version: v1
    statefulset.kubernetes.io/pod-name: flow-collection-node-v1-2

spec:
  type: ClusterIP
  selector:
    app: flow-test-net
    node: collection
    env: staging
    version: v1

  ports:
    - name: ingress
      protocol: TCP
      port: 9000
      targetPort: ingress
    - name: grpc
      protocol: TCP
      port: 3569
      targetPort: grpc

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  # This is the full name of your deployment. It must be unique
  name: flow-collection-node-v1
  namespace: flow

  # Best practice labels:
  #   app: <app-name> (the non-unique version of metadata.name)
  #   kind: [web|worker]
  #   env: [staging|production|canary|test|dev]
  #   owner: who to ask about this service
  #   version: the major version of this service (v1/v2/v1beta1)
  labels:
    app: flow-test-net
    node: collection
    env: staging
    owner: Kan
    version: v1

spec:
  replicas: 3
  serviceName: flow-test-network-v1
  selector:
    matchLabels:
      app: flow-test-net
      node: collection
      env: staging
      version: v1
  podManagementPolicy: Parallel
  template:
    metadata:
      annotations:
        # Set to "false" to opt out of prometheus scrapes
        # Prometheus still needs a port called "metrics" (below) to scrape properly
        prometheus.io/scrape: 'true'

        # Set the path to the API endpoint that exposes prometheus metrics, or leave blank for `/metrics`
        # prometheus.io/path: "/metrics"

      labels:
        app: flow-test-net
        node: collection
        env: staging
        owner: Kan
        version: v1
        kind: web

    spec:
      imagePullSecrets:
        - name: gcr
      terminationGracePeriodSeconds: 30
      containers:
        - name: flow-test-net
          # No tag, will be attached by teamcity
          image: gcr.io/dl-flow/collection
          args: 
            - '--nodename'
            - '$(POD_NAME)'
            - '--entries'
            - '$(NODE_ENTRIES)'
            - '--datadir'
            - '/flowdb'
            - '--ingress-addr'
            - ':9000'

          # Ports exposed can be named so other resources can reference
          # them by name and not have to hard code numbers
          ports:
            - name: grpc
              containerPort: 3569
            - name: http
              containerPort: 8080
            - name: ingress
              containerPort: 9000
            # Prometheus is looking specifically for a port named 'metrics'
            # This may be the same as the above port, or different
            - name: metrics
              containerPort: 8080

          # Environment variables
          env:
            - name: ENV
              value: STAGING
            # Cannot get ordinal index yet from metadata at this time: https://github.com/kubernetes/kubernetes/pull/83101/files
            # Have to parse out from pod name
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NODE_ENTRIES
              valueFrom:
                configMapKeyRef:
                  name: flow-node-config-map
                  key: entries
            - name: JAEGER_SERVICE_NAME
              value: collection
            - name: JAEGER_AGENT_HOST
              value: jaeger-agent
            - name: JAEGER_SAMPLER_TYPE
              value: const
            - name: JAEGER_SAMPLER_PARAM
              value: "1"
            - name: JAEGER_REPORTER_LOG_SPANS
              value: "true"
            # Due to the fact that we're using a headless service, we cannot use the cgo version of net,
            # which causes an error, instead, force using the pure go version now
            - name: GODEBUG
              value: "netdns=go"

          # Resource requests and contraints
          resources:
            requests:
              cpu: '125m'
              memory: '128Mi'
            limits:
              cpu: '250m'
              memory: '256Mi'
          volumeMounts:
            - name: badger-volume
              mountPath: /flowdb

          # The current liveness and readiness probes use the /metrics endpoint, which is non-ideal and MVP only
          # These probes should eventually make use of the gRPC server's Ping function, or should at least
          # be moved over to a /live endpoint that has some introspection into the gRPC's liveness/readiness

          # Readiness Probe
          readinessProbe:
            httpGet:
              path: /metrics
              port: http
            initialDelaySeconds: 5
            successThreshold: 1
          
          # Liveness Probe
          livenessProbe:
            httpGet:
              path: /metrics
              port: http
            initialDelaySeconds: 30
            periodSeconds: 30
            successThreshold: 1

  volumeClaimTemplates:
    - metadata:
        name: badger-volume
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
        storageClassName: standard
